services:
  app:
    container_name: node-application
    build:
      context: .
      dockerfile: Dockerfile
    #port mapping host post => 8090 container port is => 3000
    ports:
      - "3000:8090"
